### ISSUE TITLE
如何动态切换主题？ 设置明暗

### ISSUE THREAD

**Issue by keyboard2005** [Pcrab/hexo-highlight-shiki#12]

**Comment by Pcrab** [comment]
这个插件使用的 shiki 版本不支持自动切换，需要配置主题为 `css-variables`，自己从想要使用的主题中复制出对应的颜色并应用

```yaml
shiki:
    theme: "css-variables"
```

一个例子：
```css
html {
	--shiki-color-text: #444d56;
	--shiki-token-constant: #005cc5;
	--shiki-token-string: #032f62;
	--shiki-token-comment: #6a737d;
	--shiki-token-keyword: #d73a49;
	--shiki-token-parameter: #24292e;
	--shiki-token-function: #bb0000;
	--shiki-token-string-expression: #094993;
	--shiki-token-punctuation: #e36209;
	--shiki-token-link: #0366d6;
}

@media (prefers-color-scheme: dark) {
	html {
		--shiki-color-text: #d1d5da;
		--shiki-token-constant: #79b8ff;
		--shiki-token-string: #9ecbff;
		--shiki-token-comment: #6a737d;
		--shiki-token-keyword: #f97583;
		--shiki-token-parameter: #e1e4e8;
		--shiki-token-function: #cf8c8c;
		--shiki-token-string-expression: #a7bbd2;
		--shiki-token-punctuation: #e36209;
		--shiki-token-link: #4487d4;
	}
}
```
